name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Restore and build
        run: |
          dotnet restore
          dotnet build
          cd FsFirestore
          dotnet pack -c Release -o ../package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FsFirestore-artifacts
          path: package

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: FsFirestore-artifacts
          path: package

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Publish to nuget
        run: |
          cp ./package/FsFirestore*.nupkg FsFirestore.nupkg
          dotnet nuget push "*.nupkg" --api-key $NUGET_AUTH_TOKEN
